---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/docker-machine --version
      register: dockermachine_test_output
    - name: docker-machine --version
      debug:
        msg: '{{ dockermachine_test_output.stdout }}'
