---
- name: downloading {{ dockermachine_url }} to {{ dockermachine_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ dockermachine_url }}'
    dest: '{{ dockermachine_exe }}'
    mode: '0755'
    checksum: '{{ dockermachine_checksum }}'

- name: linking {{ dockermachine_link }} to {{ dockermachine_exe }}
  become: true
  become_user: root
  file:
    src: '{{ dockermachine_exe }}'
    dest: '{{ dockermachine_link }}'
    state: link
